# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/extra_parameters_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_extra_parameters_dialog(object):
    def setupUi(self, extra_parameters_dialog):
        extra_parameters_dialog.setObjectName("extra_parameters_dialog")
        extra_parameters_dialog.resize(244, 323)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(extra_parameters_dialog.sizePolicy().hasHeightForWidth())
        extra_parameters_dialog.setSizePolicy(sizePolicy)
        extra_parameters_dialog.setMinimumSize(QtCore.QSize(0, 0))
        extra_parameters_dialog.setMaximumSize(QtCore.QSize(99999, 99999))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/graph_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        extra_parameters_dialog.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(extra_parameters_dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(extra_parameters_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.add_parameter_button = QtWidgets.QPushButton(self.frame)
        self.add_parameter_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_parameter_button.setIcon(icon1)
        self.add_parameter_button.setObjectName("add_parameter_button")
        self.horizontalLayout_3.addWidget(self.add_parameter_button)
        self.remove_parameter_button = QtWidgets.QPushButton(self.frame)
        self.remove_parameter_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minus2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_parameter_button.setIcon(icon2)
        self.remove_parameter_button.setObjectName("remove_parameter_button")
        self.horizontalLayout_3.addWidget(self.remove_parameter_button)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.parameters_table = QtWidgets.QTableWidget(self.frame)
        self.parameters_table.setAlternatingRowColors(True)
        self.parameters_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.parameters_table.setObjectName("parameters_table")
        self.parameters_table.setColumnCount(2)
        self.parameters_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.parameters_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameters_table.setHorizontalHeaderItem(1, item)
        self.parameters_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.parameters_table, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_button = QtWidgets.QPushButton(extra_parameters_dialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(extra_parameters_dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(extra_parameters_dialog)
        QtCore.QMetaObject.connectSlotsByName(extra_parameters_dialog)

    def retranslateUi(self, extra_parameters_dialog):
        _translate = QtCore.QCoreApplication.translate
        extra_parameters_dialog.setWindowTitle(_translate("extra_parameters_dialog", "Дополнительные параметры"))
        item = self.parameters_table.horizontalHeaderItem(0)
        item.setText(_translate("extra_parameters_dialog", "Параметр"))
        item = self.parameters_table.horizontalHeaderItem(1)
        item.setText(_translate("extra_parameters_dialog", "Значение"))
        self.ok_button.setText(_translate("extra_parameters_dialog", "Ок"))
        self.cancel_button.setText(_translate("extra_parameters_dialog", "Отмена"))
import icons_rc
